import { makeStyles } from "tss-react/mui";

import { IEventCardProps } from "./EventCard.types";

export const useStyles = makeStyles<Partial<IEventCardProps>>()(
  (theme, { isSelected }) => ({
    mainContainer: {
      display: "flex",
      margin: "10px 3px 0px 10px",
      cursor: "pointer",
      "& *": { boxSizing: "border-box" },
      position: "relative",
      gap: "8px",
    },
    contentContainer: {
      backgroundColor: isSelected
        ? theme.palette.colors.gray[75]
        : theme.palette.colors.system.white,
      padding: "12px 12px 8px 12px",
      width: "100%",
      display: "flex",
      flexDirection: "column",
      justifyContent: "start",
      alignSelf: "stretch",
      borderRadius: "8px",
      borderBottom: !isSelected
        ? `1px solid ${theme.palette.colors.gray[75]}`
        : "none",
      boxShadow: isSelected ? "0px 4px 4px 0px rgba(0, 0, 0, 0.08)" : "none",
    },
    profilecontainer: {
      height: "47px",
      width: "47px",
    },
    nameCardHeader: {
      display: "flex",
      height: "52px",
      alignItems: "center",
      gap: "12px",
      alignSelf: "stretch",
    },
    nameContainer: {
      width: "calc(100% - 59px)",
      display: "flex",
      flexDirection: "column",
      gap: "8px",
    },
    profileNameHeadText: {
      display: "flex",
      height: "50px",
      flexDirection: "column",
      justifyContent: "flex-start",
      paddingLeft: "0px",
      gap: "4px",
      flex: 1,
    },
    nameContainerHead: {
      display: "flex",
      alignItems: "center",
      alignSelf: "stretch",
      gap: "16px",
    },
    avatarCon: {
      display: "flex",
      alignItems: "center",
      width: "100%",
      height: "100%",
    },
    profileDiv: {
      height: "47px",
      width: "47px",
      position: "relative",
    },
    roleName: {
      borderRadius: "4px",
      padding: "0px 0px",
      color: theme.palette.colors.gray[500],
      marginTop: "10px",
      height: "17px",
      paddingBottom: "10px",
      alignSelf: "stretch",
      textOverflow: "ellipsis",
      overflow: "hidden",
      whiteSpace: "nowrap",
      maxWidth: "80px",
    },
    roleWrapper: {
      display: "flex",
      gap: "16px",
      alignItems: "center",
      justifyContent: "space-between",
    },
    timeRange: {
      borderRadius: "4px",
      padding: "0px 0px",
      color: theme.palette.colors.gray[500],
      marginTop: "10px",
      height: "17px",
      paddingBottom: "10px",
      alignSelf: "stretch",
      textOverflow: "ellipsis",
      overflow: "hidden",
      whiteSpace: "nowrap",
    },
    userNametext: {
      color: theme.palette.colors.gray[900],
      flex: "1 0 0",
      alignSelf: "stretch",
      maxWidth: "300px",
      overflow: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
    },
    contentWrap: {
      display: "flex",
      alignItems: "center",
      gap: "16px",
      alignSelf: "stretch",
    },
    roomDotWrapper: {
      paddingTop: "12px",
      paddingBottom: "8px",
      display: "flex",
      gap: "16px",
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
    },
    roomWrapper: {
      display: "flex",
      alignItems: "center",
      gap: "16px",
      width: "40%",
    },
    dotsContainer: {
      height: "24px",
      width: "60%",
    },
    dotWrapper: {
      display: "flex",
      alignItems: "center",
      gap: "20px",
      height: "24px",
      zIndex: 1,
    },
    Wrapper: {
      flex: 1,
      border: `1px solid ${theme.palette.colors.gray[isSelected ? 50 : 100]}`,
      borderRadius: "36px",
      height: "26px",
      position: "relative",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    blueCardAlignment: {
      position: "absolute",
      right: "1px",
      top: "50%",
      transform: "translateY(-50%)",
      zIndex: 2,
    },
    countdownText: {
      fontSize: "10px",
      color: theme.palette.colors.gray[500],
    },
    progressBarWrapper: {
      position: "absolute",
      bottom: 0,
      left: 0,
      height: "2px",
      width: "100%",
      backgroundColor: theme.palette.colors.gray[200],
      borderRadius: "0 0 36px 36px",
      overflow: "hidden",
    },
    progressBar: {
      height: "100%",
      backgroundColor: theme.palette.colors.theme.primary,
      transition: "width 0.3s ease",
    },
  }),
);
